### ISSUE TITLE
vue-router-tips e vuex-tips

### ISSUE THREAD

**Issue by johanpedroo** [vuejs-tips/cheatsheet#1]
Ia fazer um post em inglês, mas vi que você é de Maringá tb kkk, achei interessante fazer um vue-tips do vue-router e vuex, é muito mais fácil achar algo pelo vuejs-tips do q ficar fuçando na doc, pensei em contibuir, mas não sei nem onde começar :(, ia ajudar bastante! Parabéns pelo trabalho! ^^

**Comment by neves** [comment]
vue-router e vuex já estão no forno, aguarde  novidades!
